// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyABZX6vZhdDqoFuN6SMILxZYn8jbsTaVBA',
    appId: '1:209943692812:android:77653d00cf08ceb69d5029',
    messagingSenderId: '209943692812',
    projectId: 'tracking-app-c66d9',
    storageBucket: 'tracking-app-c66d9.appspot.com',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyAp9GRzZNvMx9BfclXLOKoxcIYehNHkk_o',
    appId: '1:209943692812:ios:1bf6651468edfa4f9d5029',
    messagingSenderId: '209943692812',
    projectId: 'tracking-app-c66d9',
    storageBucket: 'tracking-app-c66d9.appspot.com',
    iosBundleId: 'com.tracking.app.trackingApp',
  );
}
